name: tobeto_app
description: Eğitim Projesi

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  intl: ^0.18.1
  autoscale_tabbarview: ^1.0.2
  url_launcher: ^6.2.3
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  dynamic_color: ^1.6.9
  video_player: ^2.8.2
  flick_video_player: ^0.7.0
  visibility_detector: ^0.4.0+2
  flutter_bloc: ^8.1.3
  image_picker: ^1.0.7
  firebase_storage: ^11.6.6
  fluttertoast: ^8.2.4
  flutter_localizations:
    sdk: flutter
  syncfusion_flutter_calendar: ^21.1.41
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: Tinos
      fonts:
        - asset: assets/fonts/Tinos-Regular.ttf

  uses-material-design: true

  assets:
    - assets/png/
